# Generated by Django 2.2.7 on 2019-11-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20191114_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='review_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='alumni.Users'),
        ),
        migrations.AlterField(
            model_name='businesses',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='alumni.Users'),
        ),
    ]
