# Generated by Django 2.2.7 on 2019-11-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20191115_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesses',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='message_id',
        ),
        migrations.AddField(
            model_name='businesses',
            name='bus_state',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesses',
            name='street_address',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesses',
            name='zipcode',
            field=models.TextField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responses',
            name='response',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locations',
            name='business_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='alumni.Businesses'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventlocations', to='alumni.Events'),
        ),
    ]
