# Generated by Django 2.2.7 on 2019-11-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_auto_20191115_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesses',
            old_name='bus_state',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='response_id',
        ),
        migrations.AddField(
            model_name='responses',
            name='message_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messageresponse', to='alumni.Messages'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busireview', to='alumni.Users')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userreview', to='alumni.Users')),
            ],
        ),
    ]
