# Generated by Django 2.2.7 on 2019-11-15 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20191115_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='responses',
            name='message_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageresponse', to='alumni.Messages'),
        ),
    ]
