# Generated by Django 2.2.7 on 2019-11-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
