# Generated by Django 2.2.7 on 2019-11-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0012_users_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cohort',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
