# Generated by Django 2.2.7 on 2019-11-18 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0013_users_cohort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='businessName',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='streetAddress',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='profileimage',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='users',
            name='street_address',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesses',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='alumni.Users'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='alumni.Users'),
        ),
        migrations.AlterField(
            model_name='events',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alumni.Users'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='alumni.Users'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userresponse', to='alumni.Users'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userreview', to='alumni.Users'),
        ),
        migrations.AlterField(
            model_name='user_business',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbusiness', to='alumni.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='users',
            name='zipcode',
            field=models.CharField(max_length=6),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
