# Generated by Django 2.2.7 on 2019-11-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0014_auto_20191118_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='city',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
