# Generated by Django 2.2.7 on 2019-11-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0015_events_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_name',
            new_name='event_discription',
        ),
        migrations.AddField(
            model_name='events',
            name='event_place',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
